version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/astrolabe_smart_contract
    overwrite: true
hooks:
  AfterInstall:
    - location: scripts/deploy_upgrade.sh
      timeout: 600
      runas: root